include: package:flutter_lints/flutter.yaml

linter:
  rules: 
    prefer_const_constructors : false
    file_names : false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    prefer_relative_imports: false
    type_annotate_public_apis: false
    avoid_types_on_closure_parameters: false
    sort_constructors_first: false
    prefer_generic_function_type_aliases: true
    unnecessary_lambdas: true
    use_key_in_widget_constructors: false
    avoid_print: false